<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<TITLE>Sun3 Circuit Diagrams</TITLE>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<BODY>
<h1>Here are some Sun3 related circuit diagrams<hr>
</h1>
<ul>
<li>Sun <A HREF="3_60/index.phtml">3/60</A> Rev. 58
</ul>
<hr>
If you have any Sun3 related circuit diagrams feel free to send them to me ;-)
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
