<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Archive Hardware Page</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<body>
<h1>Sun Archive Hardware Page</h1><hr>
<h3>Hardware related stuff:</h3>
<ul>
<li> Keyboard Type 3 to Type 4 <a href="kconn.phtml">connector</a>. 
<li> Sun <a href="3.60-tuning/60tuning.phtml">3/60</a> Tuning.
<li> Sun <a href="3.80-tuning/80tunemain.phtml">3/80</a> Tuning.
<li> Using a <a href="pwrsply.phtml">PC-Power-Supply</a> for your Sun.
<li> Building a <a href="scsilbk.phtml">SCSI-Loopback-Connector</a>.
</ul>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
