<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Archive Keyboardconnector</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<body>
<h1>Sun Archive Type 3 to Type 4 Keyboardconnector:</h1><hr>
<h2>Connector Pinouts:</h2>
<IMG SRC="kbdconn.gif">
<p>
<h2>Connection Path:</h2>
<IMG SRC="connect.gif">
<p>
Just connect the Pin-Numbers in the
way shown above.
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
