<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Copyright Notes</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<body>
<h1>Sun Copyright Notes</h1><hr>

<h6>
<p>
SUN MICROSYSTEMS, INC.

<p>
End-User Binary Code

<p>
SOFTWARE  LICENSE AGREEMENT

<p>
SUN IS WILLING TO LICENSE THE ACCOMPANYING MODIFICATION TO YOU ONLY
UPON THE CONDITION THAT YOU ACCEPT ALL OF THE TERMS CONTAINED IN THIS
LICENSE AGREEMENT. READ THE TERMS AND CONDITIONS OF THIS LICENSE
CAREFULLY BEFORE DOWNLOADING THE MODIFICATION. BY DOWNLOADING AND OR
USING THE MODIFICATION, YOU AGREE TO THE TERMS AND CONDITIONS OF THIS
AGREEMENT. IF YOU ARE NOT WILLING TO BE BOUND BY THIS AGREEMENT, YOU
ARE NOT AUTHORIZED TO DOWNLOAD OR USE THIS MODIFICATION.

<p>
1. License to Use. Customer is granted a royalty-free
non-exclusive and non-transferable license ("License") for the use of
the accompanying binary software modification in machine-readable form,
together with accompanying documentation, if any, ("Software"), only in
combination with the specific software previously licensed by you from
Sun with which this Modification is intended to operate.  No other use
or distribution of the Modification is authorized.

<p>
2. Restrictions. Modification is copyrighted and title to
all copies is retained by Sun and/or its licensors. Customer shall not
make copies of the Modification, other than as authorized above plus a
single copy for archival purposes and, if applicable, Customer may, for
its internal use only, print the number of copies of on-line
documentation for which it has been authorized, in which event all
proprietary rights notices on the Modification shall be reproduced and
applied. Unless enforcement of this provision is prohibited by
applicable law, Customer shall not modify, decompile, disassemble,
decrypt, extract, or otherwise reverse engineer the Modification. The
Modification is not designed or licensed for use in on-line control
equipment in hazardous environments such as operation of nuclear
facilities, aircraft navigation or control, or direct life support
machines.

<p>
3. Confidentiality. The Modification is confidential and
proprietary information of Sun and/or its licensors. Customer agrees to
take adequate steps to protect the Modification from unauthorized
disclosure or use.

<p>
4. Disclaimer of Warranty. THE MODIFICATION IS PROVIDED
"AS IS", WITHOUT A WARRANTY OF ANY KIND. EXCEPT AS SPECIFIED IN THIS
LICENSE, ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND
WARRANTIES, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, ARE HEREBY EXCLUDED TO
THE EXTENT ALLOWED BY APPLICABLE LAW.

<p>
5. Limitation of Liability. IN NO EVENT WILL SUN BE LIABLE
FOR ANY LOST REVENUE, PROFIT OR DATA, OR FOR SPECIAL, INDIRECT,
CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES HOWEVER CAUSED AND
REGARDLESS OF THE THEORY OF LIABILITY ARISING OUT OF THE USE OF OR
INABILITY TO USE SOFTWARE, EVEN IF SUN HAS BEEN ADVISED OF THE
POSSIBILITY OF SUCH DAMAGES.

<p>
6. Termination. This License is effective until
terminated. Customer may terminate this License at any time by
destroying all copies of the Modification including any documentation.
This License will terminate immediately without notice from Sun if
Customer fails to comply with any provision of this License. Upon
termination, Customer must destroy all copies of the Modification.

<p>
7. Export Regulations. The Modification, including technical data, is
subject to U.S. export control laws, including the U.S. Export
Administration Act and its associated regulations, and may be subject
to export or import regulations in other countries. Customer agrees to
comply strictly with all such regulations and acknowledges that it has
the responsibility to obtain licenses to export, re-export, or import
the Modification.

<p>
8. U.S. Government Restricted Rights. If Customer is acquiring the
Modification including accompanying documentation on behalf of the U.S.
Government, the following provisions apply. If the Modification is
supplied to the Department of Defense ("DOD"), the Modification is
subject to "Restricted Rights", as that term is defined in the DOD
Supplement to the Federal Acquisition Regulations ("DFAR") in paragraph
252.227-7013(c) (1). If the Modification is supplied to any unit or
agency of the United States Government other than DOD, the Government's
rights in the Modification will be as defined in paragraph 52.227-19(c)
(2) of the Federal Acquisition Regulations ("FAR"). Use, duplication,
reproduction or disclosure by the Government is subject to such
restrictions or successor provisions. Contractor/Manufacturer is: Sun
Microsystems, Inc., 2550 Garcia Ave., Mountain View, CA 94043.

<p>
9. Governing Law. This Agreement is made under, shall be governed by
and construed in accordance with the laws of the State of California,
U.S.A., excluding its choice of law provisions.

<p>
10. Severability. If any of the above provisions are held to be in
violation of applicable law, void, or unenforceable  in any
jurisdiction, then such provisions are herewith waived to the extent
necessary for the License to be otherwise enforceable in such
jurisdiction,   However, if in Sun's opinion deletion of any provisions
of the License by operation of this paragraph  unreasonably compromises
the rights or liabilities of Sun or its licensors, Sun reserves the
right to terminate the License and require the destruction or return of
the Modification.

<p>
11. Integration. This Agreement is the entire agreement between
Customer and Sun relating to this Modification and: (i) supersedes all
prior or contemporaneous oral or written communications, proposals and
representations with respect to its subject matter; and (ii) prevails
over any conflicting or additional terms of any quote, order,
acknowledgment, or similar communication between the parties during the
term of this Agreement. No modification to the Agreement will be
binding, unless in writing and signed by a duly authorized
representative of each party.

<p>
Part Number   801-4734-10

</h6>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
