<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Archive PAL Page</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<body>
<h1>Sun Archive PAL Page</h1><hr>
This PAL-JDECS should be used only if your PAL is/are broken and
you need replacement. The PALS are still under <a href="copyright.phtml">
Copyright </a> by SUN MICROSYSTEMS, INC. 

<hr>
<h3>PAL-Images for the following machines/parts are available:</h3>
<ul>
<li> Sun <a href="Sun3_60/pals.phtml">3/60</a> PALs</li> 
<li> Sun <a href="CG4/pals.phtml">cg4-framebuffer</a> PALs</li>
</ul>
<hr>
<h3>Info about PAL Versions:</h3>
All the Images are in JDEC-Format.
<hr>
If the distribution of this images under the above mentioned restrictions
does offend any SUN Copyrights please drop me note (Only SUN officials
accepted) and I'll close this page.
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
