<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<TITLE>Sun3/I: Memory - SIMMs</TITLE>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<BODY TEXT="#000000" BGCOLOR="#FFFFFF">
<H2><A NAME="H1_99999">Volume I: Memory</A></H2>
<H2 > SIMMs </H2>
<P >
An <TT><B>x</B></TT> indicates the SIMM(s) was installed at the factory or
included in a memory expansion option.
</P>
<B > Sun-3, Sun-3x</B>
<P><IMG src="simms.gif"></P>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?> 
