<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Archive 3/60 PAL Page</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<body>
<h1>Sun Archive 3/60 PAL Page</h1><hr>
<h3>Here are the JDEC-Images of the 3/60 PALs</h3>
<ul>
<li> <a href="1564-02.gz">1564-02</a> 
<li> <a href="1565-01.gz">1565-01</a>
<li> <a href="1566-02.gz">1566-02</a>
<li> <a href="1567-01.gz">1567-01</a>
<li> <a href="1568-01.gz">1568-01</a>
<li> <a href="1569-01.gz">1569-01</a>
<li> <a href="1570-01.gz">1570-01</a>
<li> <a href="1571-01.gz">1571-01</a>
<li> <a href="1572-02.gz">1572-02</a>
<li> <a href="1573-01.gz">1573-01</a>
<li> <a href="1574-01.gz">1574-01</a>
<li> <a href="1575-01.gz">1575-01</a>
<li> <a href="1576-01.gz">1576-01</a>
<li> <a href="1577-01.gz">1577-01</a>
<li> <a href="1578-01.gz">1578-01</a>
<li> <a href="1579-02.gz">1579-02</a>
<li> <a href="1580-01.gz">1580-01</a>
<li> <a href="1581-01.gz">1581-01</a>
<li> <a href="1582-02.gz">1582-02</a>
<li> <a href="1583-02.gz">1583-02</a>
<li> <a href="1584-01.gz">1584-01</a>
<li> <a href="1585-01.gz">1585-01</a>
<li> <a href="1586-02.gz">1586-02</a>
<li> <a href="1587-01.gz">1587-01</a>
<li> <a href="1588-01.gz">1588-01</a>
<li> <a href="1589-01.gz">1589-01</a>
<li> <a href="1590-01.gz">1590-01</a>
<li> <a href="1594-01.gz">1594-01</a>
<li> <a href="1595-01.gz">1595-01</a>
<li> <a href="1596-01.gz">1596-01</a>
<li> <a href="1597-01.gz">1597-01</a>
<li> <a href="1598-01.gz">1598-01</a>
<li> <a href="1599-01.gz">1599-01</a>
<li> <a href="1683-03.gz">1683-03</a>
</ul>
I took the PALs from a 501-1205-03 Rev. 53 Board.<br>
The average size of an image is about 400 bytes.
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
