<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Archive SunOS 4.1.1 Boottapes Page</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<body>
<h1>Sun Archive SunOS 4.1.1 Boottapes Page</h1><hr>
If you follow the URL's below you will find all the files necessary to
create boot-tapes for the selected machine. A script to generate these
tapes is included. You may use the .tar-feature of our ftp-server to
download the whole directory.
<h3>SunOS 3.5 for Sun3:</h3>
<ul>
<li><A HREF="http://www.sun3arc.org/BootTapes/3.5/sun3_sunos3.5.tar.gz">SunOS 3.5 for Sun3</A>
</ul>
<h3>SunOS 4.0.3 for Sun3:</h3>
<ul>
<li><A HREF="http://www.sun3arc.org/BootTapes/4.0.3/sunos403.tar.gz">SunOS 4.0.3 for Sun3</A>
</ul>
<h3>SunOS 4.1.1 for Sun3:</h3>
<ul>
<li><A HREF="http://www.sun3arc.org/BootTapes/Sun3/">SunOS 4.1.1 for Sun3</A>
</ul>
<h3>SunOS 4.1.1 for Sun3x:</h3>
<ul>
<li><A HREF="http://www.sun3arc.org/BootTapes/Sun3x/">SunOS 4.1.1 for Sun3x</A>
</ul>
<h3>Update to SunOS 4.1.1_U1:</h3>
<ul>
<li><A HREF="http://www.sun3arc.org/Sun-Patches/Sun_4.1.1U1.tar.gz">SunOS 4.1.1_U1 Update for Sun3/3x</A>
</ul>
<hr>
Thanx to Mr. Knieriem of SUN Germany (Research & Education) for allowing
us to put this images online!
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
