<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Archive Paper Section</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<h1>Sun Archive Paper Section</h1><hr>
<h3>Paper-Collection</h3>
<ul>
<li> <a href="SCSI-2_tech_brief.ps.gz">SCSI2 technical brief</A>
<li> <a href="SCSI-performance.ps.gz">SCSI Performance</A>
<li> <a href="SCSI_IPI_directions.ps.gz">SCSI and IPI</A>
<li> <a href="VirtualMemoryArchitecture.ps.gz">Virtual Memory Architecture</A>
<li> <a href="cached_system_architecture_for_IO.ps.gz">Cached System Architecture and IO</A>
<li> <a href="sun_systems_and_their_caches.ps.gz">Sun-Systems and their Caches</A>
</ul>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
