<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Archive FAQ Page</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>

<h1>Sun Archive FAQ Page</h1><hr>
<h3>Several FAQ's</h3>
<ul>
<li> Sun <a href="sun.hardware.FAQ">Hardware</a> FAQ</li> 
<li> Sun <a href="bootrom.phtml">bootmonitor</a> description.</li>
<li> Sun <a href="eeprom-nvram.FAQ"> EEPROM-NVRAM</a> FAQ
<li> Sun <a href="sun-nvram-hostid.faq.phtml">HostID-NVRAM in HTML</a> FAQ
<li> Sun 19" <a href="Hitachi-Monitor.FAQ">Hitachi</A> colormonitor FAQ
<li> Sun <a href="cdrom/index.htm">CD-Rom</A> FAQ
<li> How to <a href="nvram.phtml">fix</A> a 3/80 NVRAM IDPROM
</ul>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
