<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<TITLE>Sun3/I: CPU - Sun 3200</TITLE>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<H2><A NAME="H1_99999">Volume I: CPU</A></H2>
<H2>Sun 3200</H2>
<H3 > Sun-3/260/280 </H3>
<B > 501-1100 / 501-1206 </B> [0MB] <BR>
<P><IMG src="3200.gif"></P>
<HR>
<B > 501-1100 / 501-1206<BR>
Jumper Settings </B>
<P ><IMG src="3200j.gif"></P>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
