<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<TITLE>Sun3/I: CPU - Sun 3/60LE</TITLE>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<BODY TEXT="#000000" BGCOLOR="#FFFFFF">
<H2><A NAME="H1_99999">Volume I: CPU</A></H2>
<H2>Sun 3/60LE</H2>
<B > 501-1378 </B> [4MB w/o Mono] <BR>
<P><IMG src="3_60LE.gif"></P>
<HR>
<B > 501-1378 <BR>
Jumper Settings</B>
<P ><IMG src="3_60LEj.gif"></P>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
