<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<TITLE>Sun3/I: CPU - Sun 3/60</TITLE>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<BODY TEXT="#000000" BGCOLOR="#FFFFFF">
<H2><A NAME="H1_99999">Volume I: CPU</A></H2>
<H2>Sun 3/60</H2>
<B> 501-1205 </B> [4MB w Mono] <BR>
<B> 501-1322 </B> [4MB w/o Mono] <BR>
<B> 501-1334 </B> [0MB w Mono] <BR>
<B> 501-1345 </B> [0MB w/o Mono] <BR>
<P><IMG src="3_60.gif"></P>
<HR>
<B> 501-1205 / 501-1322 / 501-1334 / 501-1345 <BR>
Jumper Settings</B>
<P><IMG src="3_60j.gif"></P>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
