<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<TITLE>Sun3/I: CPU - Sun 3/80</TITLE>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<BODY TEXT="#000000" BGCOLOR="#FFFFFF">
<H2><A NAME="H1_99999">Volume I: CPU</A></H2>
<H2>Sun 3/80</H2>
<B > &gt;=501-1401-10 </B> [4MB FCC-A] <BR>
<B > 501-1401 </B> [4MB] <BR>
<B > 501-1650 </B> [4MB FCC-A] <BR>
<P><IMG src="3_80.gif"></P>
<HR>
<B > 501-1401 / 501-1650<BR>
Jumper Settings </B>
<P ><IMG src="3_80j.gif"></P>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
