<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Archive Error-Messages Page</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<body>
<h1>Sun Archive Error-Messages Page</h1><hr>
<h3>Sun3 Machines</h3>
<ul>
<li> Sun 3/50 <a href="3_50error.phtml">Errormessages </a></li>
<li> Sun 3/60 <a href="3_60error.phtml">Errormessages </a></li> 
<li> Sun 3/110 <a href="3_110error.phtml">Errormessages </a></li>
<li> Sun 3/140/150/160/180 <a href="3_145680error.phtml">Errormessages </a></li>
<li> Sun 3/260/280 <a href="3_2680error.phtml">Errormessages </a></li>
<li> Sun 3/E <a href="3_Eerror.phtml">Errormessages </a></li>
</ul>
<h3>Sun3x Machines</h3>
<ul>
<li> Sun 3/460/480 <a href="3_4680error.phtml">Errormessages </a></li>
</ul>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
