<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Archive cg4-PAL Page</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<body>
<h1>Sun Archive cg4-PAL Page</h1><hr>
<h3>Here are the JDEC-Images of the cg4-PALs</h3>
<ul>
<li> <a href="0616-02.gz">0616-02</a>
<li> <a href="0617-01.gz">0617-01</a>
<li> <a href="1591-01.gz">1591-01</a>
<li> <a href="1592-01.gz">1592-01</a>
<li> <a href="1594-01.gz">1594-01</a>
<li> <a href="1597-01.gz">1597-01</a>
<li> <a href="1598-01.gz">1598-01</a>
<li> 1612-01 is missing
<li> <a href="1613-01.gz">1613-01</a>
<li> <a href="1614-02.gz">1614-02</a>
<li> <a href="1619-01.gz">1619-01</a>
</ul>
I took the PALs from a 501-1210-06 Rev. 53 cg4.<br>
The average size of an image is about 400 bytes.
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
