<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<TITLE>Sun3/60 Circuit Diagrams</TITLE>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<BODY>
<h1>Sun3/60 (Rev. 58) related circuit diagrams<hr>
</h1>
<ul>
<li><A HREF="s1.gif" ALT="Diagram">Page 1</A> CPU and Clock
<li><A HREF="s2.gif" ALT="Diagram">Page 2</A> MMU and Diag
<li><A HREF="s3.gif" ALT="Diagram">Page 3</A> EPROM/EEPROM
<li><A HREF="s4.gif" ALT="Diagram">Page 4</A> Serial Ports
<li><A HREF="s5.gif" ALT="Diagram">Page 5</A> Ethernet
<li><A HREF="s6.gif" ALT="Diagram">Page 6</A> SCSI
<li><A HREF="s7.gif" ALT="Diagram">Page 7</A> SCSI
<li><A HREF="s8.gif" ALT="Diagram"">Page 8</A> Memory
<li><A HREF="s9.gif" ALT="Diagram">Page 9</A> SIM-Sockets 1
<li><A HREF="s10.gif" ALT="Diagram">Page 10</A> SIM-Sockets 2
<li><A HREF="s11.gif" ALT="Diagram">Page 11</A> SIM-Sockets 3 
<li><A HREF="s12.gif" ALT="Diagram">Page 12</A> VIDEO
<li><A HREF="s13.gif" ALT="Diagram">Page 13</A> VIDEO
<li><A HREF="s14.gif" ALT="Diagram">Page 14</A> Connectors
<li><A HREF="s15.gif" ALT="Diagram">Page 15</A> Misc.
</ul>
<hr>
If you have any Sun3 related circuit diagrams feel free to send them to me ;-)
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
