<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Archive 3/60 Tuning Page</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<body>
<h1>Sun Archive 3/60 Tuning Page</h1><hr>
<h3>What's possible?</h3>
<ul>
<li><a href="over.phtml">Overclocking</a>.
<li><a href="fpu.phtml">FPU</a> replacement.
<li><a href="cpu.phtml">CPU</a> replacement. 
</ul>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
