<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Archive Harddisk Page</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<h1>Sun Archive Harddisk Page</h1><hr>
<h3>Harddisk related stuff:</h3>
<ul>
<li> Master <a href="format.dat">format.dat</a> for online-use 
or as <a href="format.dat.gz"> format.dat.gz </A> file (16220 bytes).
</ul>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
