<? Include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<TITLE>Sun3 Archive</TITLE>
<? Include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<H1>Welcome to the Sun3 Archive</H1><HR>
<H3><a name="Information">Information</a></H3>
<UL>
<LI>What is the <A HREF="text/general.phtml">Sun3/3x</A> Series?
<LI>The famous <A HREF="FAQ/faq.phtml">Sun hardware FAQ</A> and others
<LI>A guide to the <A HREF="text/partnum.phtml">Sun part numbers</A>
<LI>Representation of several <A HREF="bench/bench.phtml">Benchmark</A> results
<LI><A HREF="harddisk/format.phtml">Harddisk</A> related stuff
<LI>A Paper-<A HREF="papers/papers.phtml">Collection</A>
<LI>Sun3/3x <A HREF="Errormsg/error.phtml">Errorcode</A>-Pattern
<LI>Sun3/3x <A HREF="FEH/feh.phtml">Field Engineers Handbook</A>
</UL>
<H3><a name="Hardware">Hardware</a></H3>
<UL>
<LI>Several <A HREF="ROMs/eprom.phtml">Bootprom</A> versions
<LI>Several <A HREF="PALs/pals.phtml">PAL</A> Images for the Sun3 Series
<LI>Sun3 related  <A HREF="schematics/index.phtml">circuit</A> diagrams.
<LI>Modifying your <A HREF="hardpatches/hw.phtml">Hardware</A>
</UL>
<H3><a name="OS">Operating Systems</a></H3>
<UL>
<LI>Download <A HREF="BootTapes/index.phtml">SunOS</A> for the Sun3/3x-Series
<LI>A collection of official <A HREF="Sun-Patches/archive.phtml">Patches</A> for the Sun3/3x-Series
<LI>A collection of SPECIAL and <IMG SRC="gif/y2k.gif" ALT="Year 2000"> <A HREF="Misc-Patches/archive.phtml">Patches</A> for the Sun3/3x-Series
<LI><A HREF="tune/adb-kernel.phtml">Tune your kernel</A> using adb
<LI><A HREF="install/install.phtml">SunOS Install Media</A>
<LI><A HREF="install/4.1_install.phtml">SunOS 4.1 Install FAQ</A>
<LI>A free Operating-System for the Sun3/3x-Series: <a href="NetBSD/netbsd.phtml"> NetBSD</A>
<LI>Several Ready-To-Install <A HREF="precompiled/precomp.phtml">Packages</A> for Sun3/3x
</UL>
<H3><a name="SysSoft">System Software</a></H3>
<UL>
<LI><A HREF="WAN/index.phtml">WAN-Software</A> for the Sun3/3x-Series
<LI><A HREF="Compiler/index.phtml">Compiler</A> for the Sun3/3x-Series
</UL>
<H3><a name="Misc">Misc. Stuff</a></H3>
<UL>
<LI>Other Sun3/3x-Related <A HREF="other.phtml"> Servers</A>
</UL>
<? Include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
