<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Archive Paper Section</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<h1>Sun Archive Paper Section</h1><hr>
<h3>Paper-Collection</h3>
<ul>
<li> <a href="OS/os.phtml">Operating-System</A>
<li> <a href="Hardware/hardware.phtml">Hardware</A>
<li> <a href="Perf/perf.phtml">Performance</A>
<li> <a href="Compiler/comp.phtml">Compiler</A>
</ul>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
