#!/usr/bin/env python3
#
# Regenerate the RD68884's constant ROM, rd68884_crom.sv, with a case label
# for every one of its 2048 addresses.
#
#     python3 tools/crom_dense.py SPARSE -o rtl/vendor/rd68884/gen/rd68884_crom.sv
#     python3 tools/crom_dense.py SPARSE --verify rtl/vendor/rd68884/gen/rd68884_crom.sv
#
# SPARSE is the file as upstream's tools/ucode/asm.py writes it (RD68884
# 557e806; in this repository, `git show e4c343b:rtl/vendor/rd68884/gen/
# rd68884_crom.sv`).  It labels 812 addresses and leaves the other 1,236 to
# the `default`.  Quartus builds a case with fewer than half its entries
# labelled from logic, whatever attribute it carries: 2,973 ALMs on the
# Cyclone V.  With every address labelled it infers a 2048 x 92 ROM in block
# RAM.  So this writes the same table out in full, and changes nothing else
# that is not a comment or the synthesis attribute:
#
#   * the unlabelled addresses get labels, each with the default's word (the
#     `default` stays, now unreachable);
#   * the attribute becomes Quartus's `romstyle`; Vivado's `rom_style` is one
#     Quartus does not know (warning 10335);
#   * the header says so.
#
# --verify compares the two files: the table at all 2048 addresses (with its
# SHA-256, the one tools/check_crom_mif.py prints for the .mif Quartus
# inferred), and every line that is not a comment, the attribute or a case
# label, which must be the same in both.  Exit status 0 only if they are.
#
# Running it on its own output changes nothing.

import argparse
import hashlib
import os
import re
import sys

DEPTH, WIDTH = 2048, 92
MARK = 'Sun-3_MiSTer: REGENERATED'
ENTRY = re.compile(r"^\s*11'd(\d+)\s*:\s*rom_q\s*<=\s*92'h([0-9A-Fa-f]+)\s*;\s*$")
DEFAULT = re.compile(r"^\s*default\s*:\s*rom_q\s*<=\s*92'h([0-9A-Fa-f]+)\s*;\s*$")
ATTR = re.compile(r'^\s*\(\*.*\*\)\s*$')
DECL = re.compile(r'^\s*logic\s*\[91:0\]\s*rom_q\s*;\s*$')

HEADER = '''\
// %s locally from upstream's file (RD68884 557e806)
// by this repository's tools/crom_dense.py, which changes three things and no
// word of the table (`tools/crom_dense.py --verify`, rtl/vendor/README.md):
//   * every one of the 2048 addresses has its own case label, the %s that
//     upstream leaves to the `default` written out with the default's word.
//     Quartus builds a case with fewer than half its entries labelled from
//     logic, whatever attribute it carries; with all of them labelled it
//     infers a 2048 x 92 ROM in block RAM;
//   * the attribute is Quartus's `romstyle`, not Vivado's `rom_style`, which
//     Quartus does not know;
//   * this comment.
// Do not edit it here either: rerun the script on upstream's file.
'''


def read(path):
    data = sys.stdin.buffer.read() if path == '-' else open(path, 'rb').read()
    return data.decode('ascii'), b'\r\n' in data


def parse(text, name):
    """The lines, the table, and where the case body is."""
    lines = text.replace('\r\n', '\n').split('\n')
    if not any(re.search(r'input\s+logic\s*\[10:0\]\s*addr', l) for l in lines) \
       or sum(1 for l in lines if DECL.match(l)) != 1:
        sys.exit('%s: not the 2048 x 92 rd68884_crom this script knows' % name)
    labelled, where = {}, []
    for i, l in enumerate(lines):
        m = ENTRY.match(l)
        if m:
            a = int(m.group(1))
            if a in labelled or a >= DEPTH:
                sys.exit('%s: address %d labelled twice or out of range' % (name, a))
            labelled[a] = int(m.group(2), 16)
            where.append(i)
    dflt = [(i, int(DEFAULT.match(l).group(1), 16))
            for i, l in enumerate(lines) if DEFAULT.match(l)]
    if len(dflt) != 1 or not where:
        sys.exit('%s: no case table found' % name)
    first, (last, dword) = where[0], dflt[0]
    if where != list(range(first, last)):
        sys.exit('%s: the case labels are not one block ending at the default' % name)
    if sum(l.count('rom_q <=') for l in lines) != len(labelled) + 1:
        sys.exit('%s: an assignment to rom_q this script did not parse' % name)
    table = [labelled.get(a, dword) for a in range(DEPTH)]
    return lines, table, len(labelled), dword, first, last


def sha(table):
    return hashlib.sha256(b''.join(w.to_bytes(12, 'big') for w in table)).hexdigest()


def dense(text, name):
    lines, table, n, dword, first, last = parse(text, name)
    body = ["        11'd%-4d: rom_q <= 92'h%023X;" % (a, table[a]) for a in range(DEPTH)]
    lines[first:last] = body

    decl = next(i for i, l in enumerate(lines) if DECL.match(l))
    if not ATTR.match(lines[decl - 1]):
        sys.exit('%s: no attribute on rom_q' % name)
    lines[decl - 1] = '  (* romstyle = "M10K" *)'

    if not any(MARK in l for l in lines):
        gen = next(i for i, l in enumerate(lines) if 'GENERATED by' in l)
        end = next(i for i in range(gen, len(lines)) if lines[i] == '')
        note = (HEADER % (MARK, '{:,}'.format(DEPTH - n))).rstrip('\n').split('\n')
        lines[end:end] = ['//'] + note
    return '\n'.join(lines), table, n


def skeleton(lines):
    """What is left without comments, blank lines, the attribute and labels."""
    return [l.rstrip() for l in lines
            if l.strip() and not l.lstrip().startswith('//')
            and not ATTR.match(l) and not ENTRY.match(l)]


def verify(sparse_text, sparse_name, dense_name):
    dense_text, _ = read(dense_name)
    sl, st, sn, sd, _, _ = parse(sparse_text, sparse_name)
    dl, dt, dn, dd, _, _ = parse(dense_text, dense_name)
    print('sparse: %s' % sparse_name)
    print('        %d labelled addresses, %d on the default %023X' % (sn, DEPTH - sn, sd))
    print('dense : %s' % dense_name)
    print('        %d labelled addresses, default %023X' % (dn, dd))
    bad = [a for a in range(DEPTH) if st[a] != dt[a]]
    for a in bad[:10]:
        print('  DIFF at %4d: dense %023X, sparse %023X' % (a, dt[a], st[a]))
    print('table : %d of %d words equal' % (DEPTH - len(bad), DEPTH))
    print('        sha256 sparse %s' % sha(st))
    print('        sha256 dense  %s' % sha(dt))
    ss, ds = skeleton(sl), skeleton(dl)
    same = ss == ds
    print('code  : %d lines outside comments, attribute and case labels: %s'
          % (len(ss), 'identical' if same else 'DIFFERENT'))
    if not same:
        for a, b in zip(ss, ds):
            if a != b:
                print('  sparse: %s\n  dense : %s' % (a, b))
                break
    regen = dense(sparse_text, sparse_name)[0] == dense_text.replace('\r\n', '\n')
    print('regen : the dense file is %s this script writes from the sparse one'
          % ('what' if regen else 'NOT what'))
    ok = not bad and same and dn == DEPTH and dd == sd and regen
    print('PASS' if ok else 'FAIL')
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('sparse', help="upstream's rd68884_crom.sv, or - for stdin")
    ap.add_argument('-o', '--output')
    ap.add_argument('--verify', metavar='DENSE')
    args = ap.parse_args()

    text, crlf = read(args.sparse)
    if args.verify:
        sys.exit(0 if verify(text, args.sparse, args.verify) else 1)
    if not args.output:
        ap.error('give -o or --verify')

    out, table, n = dense(text, args.sparse)
    if os.path.exists(args.output):             # keep the checkout's line ends
        crlf = b'\r\n' in open(args.output, 'rb').read()
    if crlf:
        out = out.replace('\n', '\r\n')
    with open(args.output, 'wb') as f:
        f.write(out.encode('ascii'))
    print('%s: %d labels from %d, table sha256 %s' % (args.output, DEPTH, n, sha(table)))


if __name__ == '__main__':
    main()
