<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<title>Sun Archive EPROM Page</title>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<body>
<h1>Sun Archive EPROM Page</h1><hr>
<h3>Several Sun3/60 EPROM Versions</h3>
<ul>
<li> Sun 3/60 <a href="sun3_60_v1.0.gz">V1.0</a> Bootprom</li>
<li> Sun 3/60 V1.3 Bootprom</li>
<li> Sun 3/60 <a href="sun3_60_v1.5.gz">V1.5</a> Bootprom</li>
<li> Sun 3/60 <a href="sun3_60_v1.6.gz">V1.6</a> Bootprom (Req. to load SunOS QIC-24 1/4" tapes</li>
<li> Sun 3/60 <a href="sun3_60_v1.9.gz">V1.9</a> Bootprom </li>
<li> Sun 3/60 <a href="sun3_60_v1.9.srec.gz">V1.9</a> Bootprom </li> as Motorola SRecord
<li> Sun 3/60 <a href="sun3_60_v2.8.3.gz">V2.8.3</a> Bootprom</li>
<li> Sun 3/60 <a href="sun3_60_v3.0.1.gz">V3.0.1</a> Bootprom</li> 
<li> Sun 3/60 <a href="sun3_60_v3.0.1.srec.gz">V3.0.1</a> Bootprom</li> as Motorola SRecord
</ul>
<hr>
<h3>Info about 3/60 Versions:</h3>
The V1.0 is here just for historic reasons (I can't find it in the FEH).
The V3.0.1 was the latest Version for the 3/60 and supports
QIC-150 tape-drives and the cg6.<br>
As a suggestion of Thad Floryan Motorola SRecord is now available, too.
<p> If you have an Image of a ROM missing above please send it to me.
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
