<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<TITLE>Sun3/I: Video-Graphics - Sun-3/60 CG4 Color Frame Buffer</TITLE>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<H2><A NAME="H1_99999">Volume I: Video/Graphics</A></H2>
<H2>Sun-3/60 CG4 Color Frame Buffer</H2>
<B > Sun-3/60 <BR>
501-1210 </B>
<P > <IMG src="3_60cg4.gif"></P>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
