<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr1incl.phtml" ?>
<TITLE>Sun3/I: Video-Graphics - CG6 Color Frame Buffer</TITLE>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/hdr2incl.phtml" ?>
<H2><A NAME="H1_99999">Volume I: Video/Graphics</A></H2>
<H2>CG6 Color Frame Buffer</H2>
<B > Sun-3/60/80/460/470/480 <BR>
Sun-4/110/150/310/330/350/370/380/390/470/490 <BR>
501-1374 <BR>
501-1505 </B> [w 3/80 Backpanel] <BR>
<B > 501-1532 </B>
<P > <IMG src="cg6.gif"></P>
<? include "/var/www/vhosts/sun3arc.org/htdocs/include/footer.phtml" ?>
